Robot table
kscalelabs/store pull request #19
Opened 2024-05-29 22:04 UTC by chennisden

Also set primary key as "id" for all tables and rename "columns" to "keys" ("columns" was quite misleading)

2024-05-29 22:49 UTC, chennisden commented
pretend this pr doesnt exist for now i will make a mess of things

2024-05-30 18:20 UTC, chennisden commented
This PR is "done" now, but I still wouldn't call the userauth side of db done (not even just what we currently have implemented). The logic with the auth tokens needs to *actually ping the db*

2024-05-30 18:32 UTC, chennisden commented
Im assuming add to waitlit creates a new banned user

2024-05-30 18:35 UTC, chennisden commented
rebased on master and force pushed

2024-05-30 19:40 UTC, codekansas requested changes
looks good! small requests

2024-05-30 19:40 UTC, codekansas commented on store/app/api/model.py
> +    # Id of the token itself, not the user it belongs to.
nit: capitalize "ID"

2024-05-30 19:40 UTC, codekansas commented on store/app/api/db.py
> +                gsis=[("emailIndex", "email", "S", "HASH")],
nit

```suggestion
                gsis=[
                    ("emailIndex", "email", "S", "HASH"),
                ],
```

reason is that if we add more indexes it keeps the file blame easier to parse

2024-05-30 19:40 UTC, codekansas commented on store/app/api/db.py
> +                gsis=[("ownerIndex", "owner", "S", "HASH")],
ditto here

2024-05-30 19:40 UTC, codekansas commented on store/app/api/crud/users.py
> +        token_dict = await table.query(IndexName="emailIndex", KeyConditionExpression=Key("email").eq(email))
why not `get_item` here? this should be a unique element right, not a list?

2024-05-30 19:40 UTC, codekansas commented on store/app/api/crud/base.py
> +                for n, t in itertools.chain(((n, t) for (n, t, _) in keys), ((n, t) for _, n, t, _ in gsis))
beautiful :)

2024-05-30 19:40 UTC, codekansas commented on store/app/api/crud/base.py
> +        gsis: list[tuple[str, str, Literal["S", "N", "B"], Literal["HASH", "RANGE"]]] = [],
best practice is to put these comments into a method docstring instead of next to the function arguments

ref: https://google.github.io/styleguide/pyguide.html#382-modules

2024-05-30 19:47 UTC, chennisden commented on store/app/api/model.py
> +    # Id of the token itself, not the user it belongs to.
ACK

2024-05-30 19:51 UTC, chennisden commented on store/app/api/db.py
> +                gsis=[("emailIndex", "email", "S", "HASH")],
I initially did that, `make format` is what made it all in one line. I concur, I would have written it in multiple lines, but probably best to obey the linter.

2024-05-30 19:51 UTC, chennisden commented on store/app/api/crud/base.py
> +        gsis: list[tuple[str, str, Literal["S", "N", "B"], Literal["HASH", "RANGE"]]] = [],
ACK

2024-05-30 19:54 UTC, chennisden commented on store/app/api/crud/users.py
> +        token_dict = await table.query(IndexName="emailIndex", KeyConditionExpression=Key("email").eq(email))
Unfortunately DynamoDB does not allow you to `get_item` on anything besides a primary key. It has no mechanism of enforcing uniqueness on secondary indices, which is why we have to manually check that emails are unique whenever we attempt to perform a user insertion.

Furthermore, *even after we manually enforce uniqueness*, DynamoDB still has no interest in just returning the first entry with the correct email it finds. There is no method to perform a singular query on a secondary index.

2024-05-30 22:24 UTC, codekansas commented on store/app/api/db.py
> +                gsis=[("emailIndex", "email", "S", "HASH")],
if you put a comma inside the list, black will format it this way

2024-05-30 22:51 UTC, chennisden commented on store/app/api/crud/users.py
> +        token_dict = await table.query(IndexName="emailIndex", KeyConditionExpression=Key("email").eq(email))
never mind we will only be using email for tokens

2024-05-30 23:07 UTC, chennisden commented on store/app/api/crud/users.py
> +        token_dict = await table.query(IndexName="emailIndex", KeyConditionExpression=Key("email").eq(email))
actually tokens and the entire auth structure require significant rearch. think it is worth considering using traditional cookie based auth since it is much simpler and easier to implement. (notably i believe this implementation is wrong, though how easy it is to fix is not known to me)

2024-05-31 06:14 UTC, codekansas commented
closing bc changes got moved onto later branch

2024-05-31 06:14 UTC, closed without merging