[ FEAT ] : Add Login and Signup Page
kscalelabs/store pull request #199
Opened 2024-07-29 20:45 UTC by senthil-athiban

**What does this PR do?**

This PR closes #198, which aim is to enhance the Auth Page.

**What issues does this PR fix or reference?**

Leverage React-hook-form for form management
Adding Zod for client side validations of the input
Enhancing the UI by integrating modern UI and re-usable components

2024-07-29 20:53 UTC, codekansas requested changes
maybe i'm not following what is going on here? could you add a screenshot of the page after making ui changes?

2024-07-29 20:53 UTC, codekansas commented on frontend/src/pages/Login.tsx
> +                <CardTitle>Welcome to KScaleLabs</CardTitle>
nit - can change `KScaleLabs` to `Robolist`

2024-07-29 20:53 UTC, codekansas commented on frontend/src/pages/Login.tsx
> +              </CardContent>
we don't use email + password authentication right now? maybe i'm not following what this is for

2024-07-29 20:58 UTC, senthil-athiban commented
Sure @codekansas

2024-07-29 21:00 UTC, senthil-athiban commented
@codekansas can we use tailwind css library, instead of using seperate css module?

2024-07-29 21:08 UTC, senthil-athiban commented on frontend/src/pages/Login.tsx
> +              </CardContent>
Adding credentials (email, password) + providers (github, Google) auth

2024-07-29 22:32 UTC, codekansas commented
yes, tailwind is fine, if we can make it work well with react typescript - cc @chennisden

2024-07-30 00:17 UTC, chennisden commented
> yes, tailwind is fine, if we can make it work well with react typescript - cc @chennisden

yeah i've done this before, tailwind plays perfectly fine with react ts

2024-07-30 07:23 UTC, senthil-athiban commented
@codekansas, I've added credentials + google + github provider in the Client. If we are currently supporting github provider means, we can disable the rest of the things, in future we may need this auth credentials. Your thoughts on these ?

<img width="1469" alt="Screenshot 2024-07-30 at 12 50 32 PM" src="https://github.com/user-attachments/assets/e04966d2-9eb1-45e4-9f05-43c2c32f20fa">

2024-07-30 15:53 UTC, codekansas commented
this looks great!! let's merge this

2024-07-30 18:11 UTC, codekansas approved these changes
this is incredible, nice

2024-07-30 19:50 UTC, merged