Darkmode and navbar
kscalelabs/store pull request #20
Opened 2024-05-30 00:49 UTC by is2ac2

2024-05-30 01:53 UTC, chennisden commented
I made Isaac do some force pushing. Theoretically it says that a check has failed, but the cause is a frontend test failing because of the `react-markdown` dependency. So it fails, but only for the dumbest of reasons --- the actual code itself (i.e. the code Isaac wrote) works.

2024-05-30 04:04 UTC, codekansas requested changes
left a bunch of comments - pr looks good overall though

2024-05-30 04:04 UTC, codekansas commented on frontend/src/index.css
> +  filter: none !important;
what's this for? just curious

2024-05-30 04:04 UTC, codekansas commented on frontend/src/index.css
> +  width: 100% !important;
nice :)

2024-05-30 04:04 UTC, codekansas commented on frontend/src/constants/darkModes.ts
> +const darkModes = {
nit: change to something like "colorModes" instead of "darkModes"

2024-05-30 04:04 UTC, codekansas commented on frontend/src/components/Listings.tsx
> +import "../index.css";
plz use absolute imports instead of relative

2024-05-30 04:04 UTC, codekansas commented on frontend/src/index.tsx
> +import "./index.css";
plz use absolute imports instead of relative (i guess should also fix the ./App import too)

i will add some lint thing to change these automatically at some point in the future i think

2024-05-30 04:04 UTC, codekansas commented on frontend/src/components/DarkModeToggle.tsx
> +          ☾
cool!

2024-05-30 04:04 UTC, codekansas commented on frontend/src/App.tsx
> +      <DarkModeProvider>
why have both `<ThemeProvider>` and `<DarkModeProvider>`? maybe i'm missing something

2024-05-30 04:48 UTC, is2ac2 commented on tests/test_website.py
> +        assert False, "The website is not running."
I meant to take this out of my commit- oops

2024-05-30 04:49 UTC, is2ac2 commented on frontend/src/index.css
> +  filter: none !important;
I was experimenting with ways to not invert the colors of images- didn't end up working though so I'll delete

2024-05-30 04:53 UTC, is2ac2 commented on frontend/src/App.tsx
> +      <DarkModeProvider>
Something about how I had already put DarkModeToggle and useDarkMode in components before I decided to use preexisting themes, I can try to make this cleaner at some point

2024-05-30 19:37 UTC, codekansas commented
let's fix the merge conflicts and merge this! looks good

2024-05-31 00:54 UTC, codekansas commented
closing in favor of this pr -> https://github.com/kscalelabs/store/pull/24

2024-05-31 00:54 UTC, closed without merging