[ FEAT ] : Add ability to Create and Edit RobotList using modal
kscalelabs/store pull request #225
Opened 2024-08-01 14:09 UTC by senthil-athiban

**What does this PR do?**

This PR closes #222 

**What issues does this PR fix or reference?**

- [x] Implementing a re-usable modal system to create new robot list
- [x] Utilizing the same modal for editing the existing robot list
-

2024-08-01 21:54 UTC, codekansas requested changes
great change - some small requests but otherwise looks great!

2024-08-01 21:54 UTC, codekansas commented on frontend/src/components/listing/List.tsx
> +    <>
nit: seems like we can remove this

2024-08-01 21:54 UTC, codekansas commented on frontend/src/components/listing/List.tsx
> +      </div>
this is great. ideally we could make the div here match the card size, so that stuff doesn't change size after it is loaded

2024-08-01 21:54 UTC, codekansas commented on frontend/src/components/listing/List.tsx
> +        />
let's refactor into a new component

2024-08-01 21:54 UTC, codekansas commented on frontend/src/pages/Browse.tsx
> +  const [listId, setlistId] = useState("");
nit: `setformType -> setFormType` and `setlistId -> setListId`

2024-08-01 21:54 UTC, codekansas commented on store/settings/configs/local.yaml
> +  bucket: artifacts-senthil-store
nit: revert

maybe we can make this an environment variable with a default. ref: https://omegaconf.readthedocs.io/en/2.1_branch/custom_resolvers.html#oc-env

2024-08-02 03:22 UTC, senthil-athiban commented on store/settings/configs/local.yaml
> +  bucket: artifacts-senthil-store
My bad :(

2024-08-02 06:00 UTC, senthil-athiban commented on store/settings/configs/local.yaml
> +  bucket: artifacts-senthil-store
@codekansas , CI fails, when fetching bucket variable from .env

2024-08-02 15:29 UTC, codekansas approved these changes
awesome! thanks :)

2024-08-02 15:29 UTC, merged