Implement User Authentication with JWT for Sign-up, Verification, and Login Endpoints #
kscalelabs/store pull request #260
Opened 2024-08-06 13:11 UTC by jayzalani

**What does this PR do?**
This PR implements backend functionality for user login with email and password verification. It ensures secure authentication by hashing passwords using the bcrypt library in Python. Please note that verification setup should be customized according to your specific requirements, as I am not aware of the preferred methods you may use. For more information, please refer to the attached demonstration video.

**What issues does this PR fix or reference?**
This PR addresses the issue of securely logging in users with an email and password. It hashes user passwords to enhance security. For further reference on password hashing, you can visit the bcrypt library documentation: https://www.npmjs.com/package/bcrypt

https://github.com/user-attachments/assets/c9ffcfbc-994a-4db6-b846-4eedc4eb6453

2024-08-06 16:11 UTC, codekansas requested changes
nice pr! few requests, otherwise looks good :)

2024-08-06 16:11 UTC, codekansas commented on store/app/routers/auth/email_auth.py
> +        await crud._update_item(user)
shouldn't this be `crud.verify_user`?

2024-08-06 16:11 UTC, codekansas commented on store/app/routers/auth/email_auth.py
> +        raise HTTPException(status_code=400, detail="Invalid token")
nit: prefer `status.HTTP_400_BAD_REQUEST`

2024-08-06 16:11 UTC, codekansas commented on store/app/utils/verify_email.py
> +        print(f"\n--- Email ---\nTo: {email}\nSubject: Verify your email\nBody: Please click this link to verify your email: {verify_url}\n--- End Email ---\n")
assuming this is wip? we do have smtp configured on aws but we haven't been using it

2024-08-06 16:11 UTC, codekansas commented on store/settings/environment.py
> +    debug: bool = field(default=False)
assuming this is dupe?

2024-08-06 16:42 UTC, Winston-Hsiao commented
@jayzalani There's been some changes added to master since you started development (see #236). You'll want to merge in current master and resolve the conflicts/re-test some of your signup/login flows. 

There's more covered in the PR #236 comment but main thing is that the User model covers the 3 sign up/login flows. Creation of account (via email/password, Google, and Github) should all create a row in the same User table (normalized model), if using a OAuth provider hashed_password is left empty, and a provider is set (with the OAuth token).

Hopefully you can modify what you've already done to work with the new changes. Let me know if you have any questions also happy to work with you on finishing this up. It looks great so far!

2024-08-06 22:08 UTC, chennisden commented
I see that this branch is very WIP.

For now, I have rebased master into this branch. You should see the [jayzalani-rebased](https://github.com/kscalelabs/store/tree/jayzalani-rebased) branch. It has a few fixes as well addressing Ben's comments

2024-08-06 22:13 UTC, chennisden commented
A few comments.

You do not need to add `# Add this line` to indicate your diffs. Git does that for you. In particular, it is ideal that you make smaller commits rather than putting all your changes into one big commit.

I have no idea why you merged your branch into itself.

---

Also, because Ben put some other TO-DO stuff in other parts of the code, just a note to everyone: we haven't actuall implemented token verification logic yet. The relevant comment is

`# TODO: Implement token verification logic`

so you can sed for it.

2024-08-07 17:35 UTC, jayzalani commented
Understood. I see the issues now. I'll modify the code and retest everything soon. Thanks for the feedback and support

2024-08-08 20:41 UTC, chennisden commented
Rebased on master again.

2024-08-13 20:23 UTC, closed without merging