ONNX ppo inference on MuJoCo wasm
kscalelabs/store pull request #423
Opened 2024-09-26 01:20 UTC by WT-MM

**What does this PR do?**

Adds logic to run a standing policy on MuJoCo WASM using ONNX ppo

**What issues does this PR fix or reference?**

Continuation of #419

2024-09-26 01:28 UTC, budzianowski commented
Please use the latest policy from the sim repo. It works at 50 Hz so you have to adjust the decimation parameters here.

2024-09-27 22:11 UTC, budzianowski reviewed
Remove policy_1.onnx file and other unused ones.

2024-09-27 22:11 UTC, budzianowski commented on frontend/public/examples/scenes/dora2.xml
> +<mujoco model="Dora2_yin">
Remove all dora files

2024-09-28 03:12 UTC, Winston-Hsiao requested changes
@WT-MM Looks good, but can you check the github actions workflow and resolve the linting errors yourself? I can't clone/pull your branch/fork because of conflicts, and I'm trying to finish up kernel image download.

2024-09-29 20:24 UTC, Winston-Hsiao approved these changes
LGTM

2024-09-29 20:25 UTC, merged