Parts and robots
kscalelabs/store pull request #46
Opened 2024-06-04 17:58 UTC by chennisden

glue together frontend and non user api stuff

2024-06-04 17:58 UTC, chennisden commented
fixing merge

2024-06-05 00:02 UTC, codekansas requested changes
nice

2024-06-05 00:02 UTC, codekansas commented on store/app/api/routers/main.py
> +dynamodb = boto3.resource("dynamodb")
we probably don't want to have this as a global variable - instead make database calls following the `crud` pattern, e.g., `store/app/api/crud/users.py`

2024-06-05 00:02 UTC, codekansas commented on store/app/api/routers/main.py
> +        raise HTTPException(status_code=500, detail=e.response["Error"]["Message"])
fastapi should throw 500 errors for us, right? what's the point of doing this?

2024-06-05 00:02 UTC, codekansas commented on store/app/api/routers/main.py
> +                status_code=404, detail=f"Part not {test} found {response} {table} ooga {part_id} booga"
lmao

2024-06-05 00:02 UTC, codekansas commented on store/app/api/routers/users.py
> +from store.app.api.email_utils import OneTimePassPayload, send_delete_email, send_otp_email
we can instead make a `utils` dir and move this to `utils/email.py`

2024-06-05 00:02 UTC, codekansas commented on store/settings/configs/local.yaml
> +email:
probably don't need this if we just set it in the environment config dataclass

2024-06-05 01:20 UTC, chennisden commented
Yeah there's a lot of accumulated cruft everywhere because this branch diverged from master a while ago. A lot of these things are actually regressions that I think we just failed to spot

2024-06-05 17:38 UTC, codekansas reviewed
request

2024-06-05 17:38 UTC, codekansas commented on frontend/src/App.tsx
> +                    <Route path="add_robot" element={<RobotForm />} />
add leading slash, move before 404

also, maybe we should change to `/add/robot` so that later we can do stuff like `/add/model` or whatever

2024-06-05 18:11 UTC, chennisden commented on frontend/src/pages/PartDetails.tsx
> +import rob from "hooks/rob";
Done

2024-06-05 18:17 UTC, chennisden commented on store/app/api/routers/main.py
> +dynamodb = boto3.resource("dynamodb")
Definitely not. We're using something else anyway (in crud) so deleted.

2024-06-05 18:27 UTC, chennisden commented on store/app/api/routers/main.py
> +        raise HTTPException(status_code=500, detail=e.response["Error"]["Message"])
agree

2024-06-05 19:02 UTC, chennisden commented on frontend/src/hooks/rob.tsx
> +      }
i feel like the effort to make it "generic" (there are a lot of subtly different args) would not be worthwhile atm

2024-06-05 21:45 UTC, chennisden commented
@codekansas ready to merge

2024-06-05 21:46 UTC, chennisden commented
(refactoring stuff inot crud will be next pr)

2024-06-05 21:47 UTC, codekansas approved these changes

2024-06-05 21:48 UTC, merged