Base for stripe connect onboardnig flow
kscalelabs/store pull request #528
Opened 2024-11-05 05:02 UTC by Winston-Hsiao

#WIP
**What does this PR do?**
1. Stripe Connected Account Onboarding (allow users to create an account or link existing stripe account)
2. TODO: 

<img width="1506" alt="Screenshot 2024-11-05 at 12 02 07 AM" src="https://github.com/user-attachments/assets/4fe3080d-ccab-44e4-a423-64c25fc59af2">

2024-11-06 19:42 UTC, codekansas requested changes
nice pr - big feature once we merge it. few requests, overall structure looks great

2024-11-06 19:42 UTC, codekansas commented on frontend/src/components/pages/DeleteConnect.tsx
> +    }
we shouldn't have separate behavior when developing locally vs in prod - what's the reason fro this?

2024-11-06 19:42 UTC, codekansas commented on frontend/src/components/pages/DeleteConnect.tsx
> +        navigate("/seller-onboarding");
in general we should try to organize the urls hierarchically and avoid long names with dashes. for example, rather than something like `/seller-onboarding` we should have something like `/buy/onboarding` so all the purchase-related things can go within this subroute

2024-11-06 19:42 UTC, codekansas commented on frontend/src/components/pages/DeleteConnect.tsx
> +        </h1>
hmm - i think we should have this as an option in prod for admins - will let us avoid having separate behavior in dev vs prod

2024-11-06 19:42 UTC, codekansas commented on frontend/src/components/pages/SellerDashboard.tsx
> +            ✓ Your K-Scale seller account is active and ready to receive
prefer FaIcons instead of non-ascii characters

2024-11-06 19:42 UTC, codekansas commented on frontend/src/hooks/useStripeConnect.tsx
> +export const useStripeConnect = (connectedAccountId: string | null) => {
great - good pattern

however, we should structure consumers of this function so that if `connectedAccountId` is not available, it just doesn't try to use stripe connect

2024-11-06 19:42 UTC, codekansas commented on frontend/src/hooks/useStripeConnect.tsx
> +import { useAuthentication } from "./useAuth";
plz use absolute imports, e.g., `"@/hooks/useAuth"`

2024-11-06 19:42 UTC, codekansas commented on frontend/src/hooks/useStripeConnect.tsx
> +      if (!connectedAccountId) {
just realized, this variable isn't used besides to check if it is available? we should think of a better variable name then, something like `hasConnectedAccount`

2024-11-06 19:42 UTC, codekansas commented on frontend/src/hooks/useStripeConnect.tsx
> +  >();
really shouldn't have `undefined` here. ideally we should avoid situations where there are any undefined variables

2024-11-06 19:42 UTC, codekansas commented on store/app/crud/users.py
> +        return super().get_gsis().union({"user_id", "email", "user_token", "username", "stripe_connect_account_id"})
ehhhhh adding this as a gsi seems inadvisable. there is a limit on the number of gsis we can include, i don't think we actually need to have some fast query for users with stripe connect accounts

2024-11-06 19:42 UTC, codekansas commented on store/app/crud/users.py
> +    # For testing workflow will remove once stripe connect payment and listing integration done
nit: use docstring comments instead of comments above functions like this

2024-11-06 19:42 UTC, codekansas commented on store/app/routers/stripe.py
> +@stripe_router.post("/create-connect-account", response_model=CreateConnectAccountResponse)
rather than having long url names like `/create-connect-account` - i would prefer that you make a separate router like `/connect` and add all these functions to it. will be organized better / more hierarchically

2024-11-06 19:42 UTC, codekansas commented on store/app/routers/stripe.py
> +) -> Dict[str, Any]:
let's keep this as an option that is available for admins

2024-11-06 19:42 UTC, codekansas commented on store/app/routers/stripe.py
> +@stripe_router.post("/connect-account/update-onboarding-status")
prefer urls like `/status/update` instead of `/update-onboarding-status`

2024-11-06 19:46 UTC, Winston-Hsiao commented on frontend/src/components/pages/DeleteConnect.tsx
> +    }
this is just for my dev workflow atm. We won't have this page and I will be deleting the endpoint that deletes connect-accounts. 

This will be deleted after the stripe connect and listing flow is finished with next PR.

2024-11-06 19:49 UTC, Winston-Hsiao commented on frontend/src/components/pages/DeleteConnect.tsx
> +        </h1>
Yeah I can look to make that change, can have the is_admin permission, would need to rework this though, currently it just deletes all connect accounts (so currently in the stripe developer mode), was just needed as I was constantly making new accounts like 50+ while refining the account connection/creation flow)

2024-11-07 03:56 UTC, codekansas approved these changes
few requests but overall greatly improved, nice job

2024-11-07 03:56 UTC, codekansas commented on frontend/src/components/pages/SellerOnboarding.tsx
> +  const showStripeConnect = Boolean(
lol, `Boolean`, is there a reason for this?

2024-11-07 03:56 UTC, codekansas commented on store/app/routers/stripe.py
> +        logger.info(f"Starting new account creation for user {user.id}")
nit: prefer not to use f-strings in logging
```suggestion
        logger.info("Starting new account creation for user %s", user.id)
```

2024-11-07 03:56 UTC, codekansas commented on store/app/routers/stripe.py
> +        logger.info(f"Created new Connect account: {account.id} for user: {user.id}")
nit: same as above
```suggestion
        logger.info("Created new Connect account: %s for user: %s", account.id, user.id)
```

2024-11-07 03:56 UTC, codekansas commented on store/app/routers/stripe.py
> +        raise HTTPException(status_code=500, detail=str(e))
it is not a good idea to use 500 error code, that should be reserved for things going truly wrong. if you don't want to catch specific errors, just raise the error as-is and let the fastapi error handler cast it to some default error code based on the error type (but not 500)

2024-11-07 03:59 UTC, Winston-Hsiao commented on frontend/src/components/pages/SellerOnboarding.tsx
> +  const showStripeConnect = Boolean(
nope, Cursor generated that line/paradigm. I suppose the only benefit is that we type it as a boolean strictly... even though evaluating the existence of the 2 fields will return true or false anyway. Removed

2024-11-07 04:00 UTC, Winston-Hsiao commented on store/app/routers/stripe.py
> +        logger.info(f"Created new Connect account: {account.id} for user: {user.id}")
Cool, will use format specifiers, didn't learn C in school for nothing :)

2024-11-07 04:07 UTC, merged